functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Пользователь должен иметь возможность фильтровать товары по цене, цвету, размеру и т.д.
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре.
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины.
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен иметь мобильную версию.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика.
  - Сайт должен быть доступен на различных устройствах.
implicit:
  - Пользователь должен авторизироваться перед оформлением заказа.
  - Пользователь долен иметь возможность удалять товар из корзины. 
  - Сайт должен быть мультиязычен. 
  - Пользователь должен иметь возможность просматривать историю заказов.
  - Пользователь должен иметь возможность вернуться на главную страницу, по нажатию логотипа сайта.
  - Пользователь должен иметь возможность перемещаться внутри сайта на другие страницы с товарами с помощью конопок "Предыдущая" и "Следующая".
